#TROCAR O NOME DA APLICACAO
spring.application.name=doisv
spring.jpa.open-in-view=false
spring.profiles.active=${APP_PROFILE:dev}

# CORS (default para ambiente local)
cors.origins=http://localhost:5500